#数据库连接池
spring:
  datasource:
    url: jdbc:mysql://106.14.81.50:3306/eld_care?serverTimezone=GMT&characterEncoding=utf8&useSSL=false
    username: remote
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
#关闭 Thymeleaf 的缓存开发过程中无需重启
  thymeleaf:
    cache: false
#设置thymeleaf页面的编码
    encoding: UTF-8
    mode: HTML5
#设置thymeleaf页面的后缀
    suffix : .html
#设置thymeleaf页面的存储路径
    prefix: classpath:/templates/
server:
  port: 9090

logging:
  level:
    com:
      eldcare:
        main:
          mapper : debug
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.eldcare.main.entity